# Generated by Django 5.1.6 on 2025-03-11 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('track', models.ManyToManyField(help_text='Select a track for this playlist', to='catalog.trackinstance')),
            ],
            options={
                'ordering': ['date_added'],
            },
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(help_text='Select an artist for this track', to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.genre'),
        ),
    ]
