# Generated by Django 5.1.6 on 2025-03-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_artist_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'permissions': (('can_create_public_artist', 'Artist - Create Public'), ('can_create_any_artist', 'Artist - Create Any'), ('can_view_public_artist', 'Artist - View Public'), ('can_view_any_artist', 'Artist - View Any'), ('can_modify_public_artist', 'Artist - Modify Public'), ('can_modify_any_artist', 'Artist - Modify Any'))},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'permissions': (('can_create_public_genre', 'Genre - Create Public'), ('can_create_any_genre', 'Genre - Create Any'), ('can_view_public_genre', 'Genre - View Public'), ('can_view_any_genre', 'Genre - View Any'), ('can_modify_public_genre', 'Genre - Modify Public'), ('can_modify_any_genre', 'Genre - Modify Any'))},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['date_added'], 'permissions': (('can_create_own_playlist', 'Playlist - Create Own'), ('can_create_any_playlist', 'Playlist - Create Any'), ('can_view_own_playlist', 'Playlist - View Own'), ('can_view_public_playlist', 'Playlist - View Public'), ('can_view_any_playlist', 'Playlist - View Any'), ('can_modify_own_playlist', 'Playlist - Modify Own'), ('can_modify_public_playlist', 'Playlist - Modify Public'), ('can_modify_any_playlist', 'Playlist - Modify Any'))},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['type', 'date_added'], 'permissions': (('can_create_own_tag', 'Tag - Create Own'), ('can_create_any_tag', 'Tag - Create Any'), ('can_view_own_tag', 'Tag - View Own'), ('can_view_public_tag', 'Tag - View Public'), ('can_view_any_tag', 'Tag - View Any'), ('can_modify_own_tag', 'Tag - Modify Own'), ('can_modify_public_tag', 'Tag - Modify Public'), ('can_modify_any_tag', 'Tag - Modify Any'))},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['title'], 'permissions': (('can_create_public_track', 'Track - Create Public'), ('can_create_any_track', 'Track - Create Any'), ('can_view_public_track', 'Track - View Public'), ('can_view_any_track', 'Track - View Any'), ('can_modify_public_track', 'Track - Modify Public'), ('can_modify_any_track', 'Track - Modify Any'))},
        ),
        migrations.AlterModelOptions(
            name='trackinstance',
            options={'ordering': ['date_added'], 'permissions': (('can_create_own_trackinstance', 'Track Instance - Create Own'), ('can_create_any_trackinstance', 'Track Instance - Create Any'), ('can_view_own_trackinstance', 'Track Instance - View Own'), ('can_view_public_trackinstance', 'Track Instance - View Public'), ('can_view_any_trackinstance', 'Track Instance - View Any'), ('can_modify_own_trackinstance', 'Track Instance - Modify Own'), ('can_modify_public_trackinstance', 'Track Instance - Modify Public'), ('can_modify_any_trackinstance', 'Track Instance - Modify Any'))},
        ),
        migrations.AddField(
            model_name='artist',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
