# Generated by Django 5.1.6 on 2025-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_track_artist_remove_track_genre_playlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinstance',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='beatport_track_id',
            field=models.BigIntegerField(help_text='Track ID from Beatport, found in the track URL, which can be used to populate metadata.', unique=True, verbose_name='Beatport Track ID'),
        ),
    ]
