# Generated by Django 5.1.6 on 2025-03-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_trackinstance_play_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinstance',
            name='rating',
            field=models.CharField(blank=True, choices=[('a', 'Awesome'), ('f', 'Fine'), ('t', 'Terrible')], default='f', help_text='Track rating', max_length=1),
        ),
    ]
