# Generated by Django 5.1.6 on 2025-03-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_trackinstance_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinstance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackinstance',
            name='rating',
            field=models.CharField(blank=True, choices=[(0, 'Unplayable'), (1, 'Atrocious'), (2, 'Terrible'), (3, 'Bad'), (4, 'Meh'), (5, 'Okay'), (6, 'Fine'), (7, 'Good'), (8, 'Great'), (9, 'Excellent'), (10, 'Perfect')], default=None, help_text='Track rating', max_length=1),
        ),
    ]
