# Generated by Django 5.1.6 on 2025-03-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_artist_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'permissions': (('moxtool_can_create_public_artist', 'Artist - Create Public - DJ'), ('moxtool_can_create_any_artist', 'Artist - Create Any - MOX'), ('moxtool_can_view_public_artist', 'Artist - View Public - DJ'), ('moxtool_can_view_any_artist', 'Artist - View Any - MOX'), ('moxtool_can_modify_public_artist', 'Artist - Modify Public - DJ'), ('moxtool_can_modify_any_artist', 'Artist - Modify Any - MOX'))},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'permissions': (('moxtool_can_create_public_genre', 'Genre - Create Public - DJ'), ('moxtool_can_create_any_genre', 'Genre - Create Any - MOX'), ('moxtool_can_view_public_genre', 'Genre - View Public - DJ'), ('moxtool_can_view_any_genre', 'Genre - View Any - MOX'), ('moxtool_can_modify_public_genre', 'Genre - Modify Public - DJ'), ('moxtool_can_modify_any_genre', 'Genre - Modify Any - MOX'))},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['date_added'], 'permissions': (('moxtool_can_create_own_playlist', 'Playlist - Create Own - DJ'), ('moxtool_can_create_any_playlist', 'Playlist - Create Any - MOX'), ('moxtool_can_view_own_playlist', 'Playlist - View Own - DJ'), ('moxtool_can_view_public_playlist', 'Playlist - View Public - DJ'), ('moxtool_can_view_any_playlist', 'Playlist - View Any - MOX'), ('moxtool_can_modify_own_playlist', 'Playlist - Modify Own - DJ'), ('moxtool_can_modify_public_playlist', 'Playlist - Modify Public - DJ'), ('moxtool_can_modify_any_playlist', 'Playlist - Modify Any - MOX'))},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['type', 'date_added'], 'permissions': (('moxtool_can_create_own_tag', 'Tag - Create Own - DJ'), ('moxtool_can_create_any_tag', 'Tag - Create Any - MOX'), ('moxtool_can_view_own_tag', 'Tag - View Own - DJ'), ('moxtool_can_view_public_tag', 'Tag - View Public - DJ'), ('moxtool_can_view_any_tag', 'Tag - View Any - MOX'), ('moxtool_can_modify_own_tag', 'Tag - Modify Own - DJ'), ('moxtool_can_modify_public_tag', 'Tag - Modify Public - DJ'), ('moxtool_can_modify_any_tag', 'Tag - Modify Any - MOX'))},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['title'], 'permissions': (('moxtool_can_create_public_track', 'Track - Create Public - DJ'), ('moxtool_can_create_any_track', 'Track - Create Any - MOX'), ('moxtool_can_view_public_track', 'Track - View Public - DJ'), ('moxtool_can_view_any_track', 'Track - View Any - MOX'), ('moxtool_can_modify_public_track', 'Track - Modify Public - DJ'), ('moxtool_can_modify_any_track', 'Track - Modify Any - MOX'))},
        ),
        migrations.AlterModelOptions(
            name='trackinstance',
            options={'ordering': ['date_added'], 'permissions': (('moxtool_can_create_own_trackinstance', 'Track Instance - Create Own - DJ'), ('moxtool_can_create_any_trackinstance', 'Track Instance - Create Any - MOX'), ('moxtool_can_view_own_trackinstance', 'Track Instance - View Own - DJ'), ('moxtool_can_view_public_trackinstance', 'Track Instance - View Public - DJ'), ('moxtool_can_view_any_trackinstance', 'Track Instance - View Any - MOX'), ('moxtool_can_modify_own_trackinstance', 'Track Instance - Modify Own - DJ'), ('moxtool_can_modify_public_trackinstance', 'Track Instance - Modify Public - DJ'), ('moxtool_can_modify_any_trackinstance', 'Track Instance - Modify Any - MOX'))},
        ),
    ]
