# Generated by Django 5.1.6 on 2025-03-13 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_trackinstance_user_alter_trackinstance_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(blank=True, choices=[('t', 'track'), ('p', 'playlist')], default=None, help_text='Object of a tag (e.g. track)', max_length=8)),
                ('tag_type', models.CharField(blank=True, choices=[('v', 'vibe'), ('c', 'color'), ('h', 'chords'), ('s', 'sounds'), ('g', 'groove')], default=None, help_text='Type of tag (e.g. vibe)', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackinstance',
            name='rating',
            field=models.CharField(blank=True, choices=[('0', 'Unplayable'), ('1', 'Atrocious'), ('2', 'Terrible'), ('3', 'Bad'), ('4', 'Meh'), ('5', 'Okay'), ('6', 'Fine'), ('7', 'Good'), ('8', 'Great'), ('9', 'Excellent'), ('10', 'Perfect')], default=None, help_text='Track rating', max_length=2),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tag',
            field=models.ManyToManyField(help_text='Select a tag for this playlist', to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='trackinstance',
            name='tag',
            field=models.ManyToManyField(help_text='Select a tag for this track', to='catalog.tag'),
        ),
    ]
