# Generated by Django 5.1.6 on 2025-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_artist_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(help_text='Select an artist for this track', null=True, to='catalog.artist'),
        ),
    ]
