# Generated by Django 5.1.6 on 2025-03-18 14:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_track_mix_track_remix_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'permissions': (('moxtool_can_create_own_artist', 'Artist - Create Own - DJ'), ('moxtool_can_create_any_artist', 'Artist - Create Any - MOX'), ('moxtool_can_view_public_artist', 'Artist - View Public - DJ'), ('moxtool_can_view_own_artist', 'Artist - View Own - DJ'), ('moxtool_can_view_any_artist', 'Artist - View Any - MOX'), ('moxtool_can_modify_public_artist', 'Artist - Modify Public - DJ'), ('moxtool_can_modify_own_artist', 'Artist - Modify Own - DJ'), ('moxtool_can_modify_any_artist', 'Artist - Modify Any - MOX'))},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'permissions': (('moxtool_can_create_own_genre', 'Genre - Create Own - DJ'), ('moxtool_can_create_any_genre', 'Genre - Create Any - MOX'), ('moxtool_can_view_public_genre', 'Genre - View Public - DJ'), ('moxtool_can_view_own_genre', 'Genre - View Own - DJ'), ('moxtool_can_view_any_genre', 'Genre - View Any - MOX'), ('moxtool_can_modify_public_genre', 'Genre - Modify Public - DJ'), ('moxtool_can_modify_own_genre', 'Genre - Modify Own - DJ'), ('moxtool_can_modify_any_genre', 'Genre - Modify Any - MOX'))},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['title'], 'permissions': (('moxtool_can_create_own_track', 'Track - Create Own - DJ'), ('moxtool_can_create_any_track', 'Track - Create Any - MOX'), ('moxtool_can_view_public_track', 'Track - View Public - DJ'), ('moxtool_can_view_own_track', 'Track - View Own - DJ'), ('moxtool_can_view_any_track', 'Track - View Any - MOX'), ('moxtool_can_modify_public_track', 'Track - Modify Public - DJ'), ('moxtool_can_modify_own_track', 'Track - Modify Own - DJ'), ('moxtool_can_modify_any_track', 'Track - Modify Any - MOX'))},
        ),
        migrations.CreateModel(
            name='ArtistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('date_requested', models.DateField(default=datetime.date(2025, 3, 18))),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.artist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_requested', 'name'],
                'permissions': (('moxtool_can_create_own_artistrequest', 'ArtistRequest - Create Own - DJ'), ('moxtool_can_create_any_artistrequest', 'ArtistRequest - Create Any - MOX'), ('moxtool_can_view_own_artistrequest', 'ArtistRequest - View Own - DJ'), ('moxtool_can_view_any_artistrequest', 'ArtistRequest - View Any - MOX'), ('moxtool_can_modify_own_artistrequest', 'ArtistRequest - Modify Own - DJ'), ('moxtool_can_modify_any_artistrequest', 'ArtistRequest - Modify Any - MOX')),
            },
        ),
        migrations.CreateModel(
            name='GenreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('date_requested', models.DateField(default=datetime.date(2025, 3, 18))),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.artist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_requested', 'name'],
                'permissions': (('moxtool_can_create_own_genrerequest', 'GenreRequest - Create Own - DJ'), ('moxtool_can_create_any_genrerequest', 'GenreRequest - Create Any - MOX'), ('moxtool_can_view_own_genrerequest', 'GenreRequest - View Own - DJ'), ('moxtool_can_view_any_genrerequest', 'GenreRequest - View Any - MOX'), ('moxtool_can_modify_own_genrerequest', 'GenreRequest - Modify Own - DJ'), ('moxtool_can_modify_any_genrerequest', 'GenreRequest - Modify Any - MOX')),
            },
        ),
        migrations.CreateModel(
            name='TrackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatport_track_id', models.BigIntegerField(help_text='Track ID from Beatport, found in the track URL, which can be used to populate metadata.', unique=True, verbose_name='Beatport Track ID')),
                ('title', models.CharField(max_length=200)),
                ('mix', models.CharField(blank=True, choices=[('o', 'Original Mix'), ('e', 'Extended Mix'), ('x', 'Remix'), ('r', 'Radio Mix')], default=None, help_text='the mix version of the track (e.g. Original Mix, Remix, etc.)', max_length=12, null=True)),
                ('public', models.BooleanField(default=False)),
                ('date_requested', models.DateField(default=datetime.date(2025, 3, 18))),
                ('artist', models.ManyToManyField(help_text='Select an artist for this track', related_name='request_artist', to='catalog.artist')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.genre')),
                ('remix_artist', models.ManyToManyField(blank=True, help_text='Select a remix artist for this track', related_name='request_remix_artist', to='catalog.artist')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_requested', 'title'],
                'permissions': (('moxtool_can_create_own_trackrequest', 'TrackRequest - Create Own - DJ'), ('moxtool_can_create_any_trackrequest', 'TrackRequest - Create Any - MOX'), ('moxtool_can_view_own_trackrequest', 'TrackRequest - View Own - DJ'), ('moxtool_can_view_any_trackrequest', 'TrackRequest - View Any - MOX'), ('moxtool_can_modify_own_trackrequest', 'TrackRequest - Modify Own - DJ'), ('moxtool_can_modify_any_trackrequest', 'TrackRequest - Modify Any - MOX')),
            },
        ),
    ]
