# Generated by Django 5.1.6 on 2025-03-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_track_mix_track_remix_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'permissions': (('moxtool_can_create_public_artist', 'Artist - Create Public - DJ'), ('moxtool_can_create_own_artist', 'Artist - Create Own - DJ'), ('moxtool_can_create_any_artist', 'Artist - Create Any - MOX'), ('moxtool_can_view_public_artist', 'Artist - View Public - DJ'), ('moxtool_can_view_own_artist', 'Artist - View Own - DJ'), ('moxtool_can_view_any_artist', 'Artist - View Any - MOX'), ('moxtool_can_modify_public_artist', 'Artist - Modify Public - DJ'), ('moxtool_can_modify_own_artist', 'Artist - Modify Public - DJ'), ('moxtool_can_modify_any_artist', 'Artist - Modify Any - MOX'))},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'permissions': (('moxtool_can_create_public_genre', 'Genre - Create Public - DJ'), ('moxtool_can_create_own_genre', 'Genre - Create Own - DJ'), ('moxtool_can_create_any_genre', 'Genre - Create Any - MOX'), ('moxtool_can_view_public_genre', 'Genre - View Public - DJ'), ('moxtool_can_view_own_genre', 'Genre - View Own - DJ'), ('moxtool_can_view_any_genre', 'Genre - View Any - MOX'), ('moxtool_can_modify_public_genre', 'Genre - Modify Public - DJ'), ('moxtool_can_modify_own_genre', 'Genre - Modify Own - DJ'), ('moxtool_can_modify_any_genre', 'Genre - Modify Any - MOX'))},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['title'], 'permissions': (('moxtool_can_create_public_track', 'Track - Create Public - DJ'), ('moxtool_can_create_own_track', 'Track - Create Own - DJ'), ('moxtool_can_create_any_track', 'Track - Create Any - MOX'), ('moxtool_can_view_public_track', 'Track - View Public - DJ'), ('moxtool_can_view_own_track', 'Track - View Own - DJ'), ('moxtool_can_view_any_track', 'Track - View Any - MOX'), ('moxtool_can_modify_public_track', 'Track - Modify Public - DJ'), ('moxtool_can_modify_own_track', 'Track - Modify Own - DJ'), ('moxtool_can_modify_any_track', 'Track - Modify Any - MOX'))},
        ),
    ]
