# Generated by Django 5.1.6 on 2025-03-18 17:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_artist_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='artist_name_case_insensitive_unique', violation_error_message='Artist already exists (case insensiitive match)'),
        ),
    ]
