# Generated by Django 5.1.6 on 2025-03-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_artist_artist_name_case_insensitive_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistrequest',
            name='date_requested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genrerequest',
            name='date_requested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackrequest',
            name='date_requested',
            field=models.DateField(blank=True, null=True),
        ),
    ]
