# Generated by Django 5.1.6 on 2025-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_artistrequest_date_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='beatport_track_id',
            field=models.BigIntegerField(help_text='Track ID from Beatport, found in the track URL, which can be used to populate metadata.', verbose_name='Beatport Track ID'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(models.F('beatport_track_id'), condition=models.Q(('beatport_track_id__isnull', False)), name='beatport_track_id_if_set_unique', violation_error_message='This track ID from Beatport is already attached to another track.'),
        ),
    ]
