# Generated by Django 5.1.6 on 2025-03-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_track_beatport_track_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackrequest',
            name='beatport_track_id',
            field=models.BigIntegerField(help_text='Track ID from Beatport, found in the track URL, which can be used to populate metadata.', verbose_name='Beatport Track ID'),
        ),
    ]
