# Generated by Django 5.1.6 on 2025-03-26 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_trackrequest_beatport_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrerequest',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='trackrequest',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='request_genre', to='catalog.genre'),
        ),
    ]
