# Generated by Django 5.1.6 on 2025-03-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_artist_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Select one or more tags for this playlist.', to='catalog.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(help_text='Select one or more tracks for this playlist.', to='catalog.trackinstance', verbose_name='tracks'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(blank=True, choices=[('v', 'vibe'), ('c', 'color'), ('h', 'chords'), ('s', 'sounds'), ('g', 'groove')], default=None, help_text='Type of tag (e.g. vibe, chords, etc.)', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
