# Generated by Django 5.2 on 2025-04-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_trackinstance_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='beatport_artist_id',
            field=models.BigIntegerField(help_text='Artist ID from Beatport, found in the artist URL, which can be used to populate metadata.', null=True, verbose_name='Beatport Artist ID'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='beatport_genre_id',
            field=models.BigIntegerField(help_text='Genre ID from Beatport, found in the genre URL, which can be used to populate metadata.', null=True, verbose_name='Beatport Genre ID'),
        ),
        migrations.AlterField(
            model_name='label',
            name='beatport_label_id',
            field=models.BigIntegerField(help_text='Label ID from Beatport, found in the label URL, which can be used to populate metadata.', null=True, verbose_name='Beatport Label ID'),
        ),
        migrations.AlterField(
            model_name='track',
            name='beatport_track_id',
            field=models.BigIntegerField(help_text='Track ID from Beatport, found in the track URL, which can be used to populate metadata.', null=True, verbose_name='Beatport Track ID'),
        ),
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.CheckConstraint(condition=models.Q(('beatport_artist_id__isnull', False), ('name__isnull', False), _connector='OR'), name='artist_name_or_beatport_id_is_not_null'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.CheckConstraint(condition=models.Q(('beatport_genre_id__isnull', False), ('name__isnull', False), _connector='OR'), name='genre_name_or_beatport_id_is_not_null'),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.CheckConstraint(condition=models.Q(('beatport_label_id__isnull', False), ('name__isnull', False), _connector='OR'), name='label_name_or_beatport_id_is_not_null'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.CheckConstraint(condition=models.Q(('beatport_track_id__isnull', False), ('title__isnull', False), _connector='OR'), name='track_title_or_beatport_id_is_not_null'),
        ),
    ]
