# Generated by Django 5.2 on 2025-04-09 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_artist_beatport_artist_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artistrequest',
            name='beatport_artist_id',
            field=models.BigIntegerField(help_text='Artist ID from Beatport, found in the artist URL, which can be used to populate metadata', null=True, verbose_name='Beatport Artist ID'),
        ),
        migrations.AddField(
            model_name='genrerequest',
            name='beatport_genre_id',
            field=models.BigIntegerField(help_text='Genre ID from Beatport, found in the genre URL, which can be used to populate metadata', null=True, verbose_name='Beatport Genre ID'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='beatport_artist_id',
            field=models.BigIntegerField(help_text='Artist ID from Beatport, found in the artist URL, which can be used to populate metadata', null=True, verbose_name='Beatport Artist ID'),
        ),
        migrations.AlterField(
            model_name='artistrequest',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='beatport_genre_id',
            field=models.BigIntegerField(help_text='Genre ID from Beatport, found in the genre URL, which can be used to populate metadata', null=True, verbose_name='Beatport Genre ID'),
        ),
        migrations.AddConstraint(
            model_name='artistrequest',
            constraint=models.CheckConstraint(condition=models.Q(('beatport_artist_id__isnull', False), ('name__isnull', False), _connector='OR'), name='request_artist_name_or_beatport_id_is_not_null'),
        ),
    ]
