# Generated by Django 5.2 on 2025-04-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_remove_artist_beatport_artist_id_if_set_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackrequest',
            name='beatport_track_id',
            field=models.BigIntegerField(help_text='Track ID from Beatport, found in the track URL, which can be used to populate metadata.', null=True, verbose_name='Beatport Track ID'),
        ),
    ]
