# Generated by Django 5.2 on 2025-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_trackrequest_beatport_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a dance music genre (e.g. Progressive House, Future Bass, etc.)', max_length=200, null=True),
        ),
    ]
