# Generated by Django 5.2 on 2025-04-09 21:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_genre_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='beatport_label_id',
            field=models.BigIntegerField(help_text='Label ID from Beatport, found in the label URL, which can be used to populate metadata', null=True, verbose_name='Beatport Label ID'),
        ),
        migrations.AlterField(
            model_name='track',
            name='beatport_track_id',
            field=models.BigIntegerField(help_text='Track ID from Beatport, found in the track URL, which can be used to populate metadata', null=True, verbose_name='Beatport Track ID'),
        ),
        migrations.AlterField(
            model_name='track',
            name='mix',
            field=models.CharField(help_text='The mix version of the track (e.g. Original Mix, Remix, etc.)', max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='genrerequest',
            constraint=models.CheckConstraint(condition=models.Q(('beatport_genre_id__isnull', False), ('name__isnull', False), _connector='OR'), name='request_genre_name_or_beatport_id_is_not_null'),
        ),
        migrations.AddConstraint(
            model_name='trackrequest',
            constraint=models.CheckConstraint(condition=models.Q(('beatport_track_id__isnull', False), ('title__isnull', False), _connector='OR'), name='request_track_title_or_beatport_id_is_not_null'),
        ),
    ]
