# Generated by Django 5.2 on 2025-04-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_label_beatport_label_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrerequest',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
