# Generated by Django 5.2 on 2025-04-10 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_remove_setlistitem_trackinstance_setlistitem_track_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(help_text='Type of tag (e.g. vibe, chords, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('value', 'type', 'user'), name='tag_unique_on_value_type_and_user'),
        ),
    ]
