# Generated by Django 5.2 on 2025-04-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_tag_type_alter_tag_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='detail',
            field=models.CharField(help_text='Optional detail for tag', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(help_text='Optional type of tag (e.g. vibe, chords, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(help_text='Value of tag (e.g. Nasty House, Piano Tracks)', max_length=100),
        ),
    ]
