# Generated by Django 5.2 on 2025-04-10 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_remove_tag_tag_unique_on_value_type_and_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='tag_unique_on_value_type_and_user',
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(default='', help_text='Optional type of tag (e.g. vibe, chords, etc.)', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('value', 'type', 'user'), name='tag_unique_on_value_type_and_user'),
        ),
    ]
