# Generated by Django 5.2 on 2025-04-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_remove_tag_tag_unique_on_value_type_and_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='comments',
            field=models.TextField(help_text='Enter any notes you want to remember about this setlist.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='setlist',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Select one or more tags for this setlist.', to='catalog.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='setlistitem',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
