# Generated by Django 5.2 on 2025-04-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_alter_setlist_comments_alter_setlist_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='comments',
            field=models.TextField(help_text='Enter any notes you want to remember about this setlist.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='setlistitem',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transition',
            name='comments',
            field=models.TextField(help_text='Enter any notes you want to remember about this transition.', max_length=1000, null=True),
        ),
    ]
