# Generated by Django 5.2 on 2025-04-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_setlist_comments_alter_setlistitem_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='rating',
            field=models.CharField(choices=[('0', 'unplayable'), ('1', 'atrocious'), ('2', 'terrible'), ('3', 'bad'), ('4', 'meh'), ('5', 'okay'), ('6', 'fine'), ('7', 'good'), ('8', 'great'), ('9', 'excellent'), ('10', 'perfect')], default=None, help_text='Transition rating', max_length=2, null=True),
        ),
    ]
