# Generated by Django 5.2 on 2025-05-21 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_track404'),
    ]

    operations = [
        migrations.AddField(
            model_name='track404',
            name='datetime_discovered',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 15, 17, 26, 919798), verbose_name='Date & Time Discovered'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Artist404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatport_artist_id', models.BigIntegerField(verbose_name='Beatport Artist ID')),
                ('datetime_discovered', models.DateTimeField(verbose_name='Date & Time Discovered')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('beatport_artist_id',), name='beatport_artist_id_unique', violation_error_message='This artist ID from Beatport is already marked as 404.')],
            },
        ),
        migrations.CreateModel(
            name='Genre404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatport_genre_id', models.BigIntegerField(verbose_name='Beatport Genre ID')),
                ('datetime_discovered', models.DateTimeField(verbose_name='Date & Time Discovered')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('beatport_genre_id',), name='beatport_genre_id_unique', violation_error_message='This genre ID from Beatport is already marked as 404.')],
            },
        ),
        migrations.CreateModel(
            name='Label404',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatport_label_id', models.BigIntegerField(verbose_name='Beatport Label ID')),
                ('datetime_discovered', models.DateTimeField(verbose_name='Date & Time Discovered')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('beatport_label_id',), name='beatport_label_id_unique', violation_error_message='This label ID from Beatport is already marked as 404.')],
            },
        ),
    ]
