# Generated by Django 5.2 on 2025-05-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_track404_datetime_discovered_artist404_genre404_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatport_artist_id', models.BigIntegerField(verbose_name='Beatport Artist ID')),
                ('datetime_discovered', models.DateTimeField(verbose_name='Date & Time Discovered')),
            ],
        ),
        migrations.CreateModel(
            name='GenreBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatport_genre_id', models.BigIntegerField(verbose_name='Beatport Genre ID')),
                ('datetime_discovered', models.DateTimeField(verbose_name='Date & Time Discovered')),
            ],
        ),
        migrations.CreateModel(
            name='LabelBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatport_label_id', models.BigIntegerField(verbose_name='Beatport Label ID')),
                ('datetime_discovered', models.DateTimeField(verbose_name='Date & Time Discovered')),
            ],
        ),
        migrations.CreateModel(
            name='TrackBacklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatport_track_id', models.BigIntegerField(verbose_name='Beatport Track ID')),
                ('datetime_discovered', models.DateTimeField(verbose_name='Date & Time Discovered')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='artist404',
            name='beatport_artist_id_unique',
        ),
        migrations.RemoveConstraint(
            model_name='genre404',
            name='beatport_genre_id_unique',
        ),
        migrations.RemoveConstraint(
            model_name='label404',
            name='beatport_label_id_unique',
        ),
        migrations.RemoveConstraint(
            model_name='track404',
            name='beatport_track_id_unique',
        ),
        migrations.AddConstraint(
            model_name='artist404',
            constraint=models.UniqueConstraint(fields=('beatport_artist_id',), name='beatport_artist_id_unique_404', violation_error_message='This artist ID from Beatport is already marked as 404.'),
        ),
        migrations.AddConstraint(
            model_name='genre404',
            constraint=models.UniqueConstraint(fields=('beatport_genre_id',), name='beatport_genre_id_unique_404', violation_error_message='This genre ID from Beatport is already marked as 404.'),
        ),
        migrations.AddConstraint(
            model_name='label404',
            constraint=models.UniqueConstraint(fields=('beatport_label_id',), name='beatport_label_id_unique_404', violation_error_message='This label ID from Beatport is already marked as 404.'),
        ),
        migrations.AddConstraint(
            model_name='track404',
            constraint=models.UniqueConstraint(fields=('beatport_track_id',), name='beatport_track_id_unique_404', violation_error_message='This track ID from Beatport is already marked as 404.'),
        ),
        migrations.AddConstraint(
            model_name='artistbacklog',
            constraint=models.UniqueConstraint(fields=('beatport_artist_id',), name='beatport_artist_id_unique_backlog', violation_error_message='This artist ID from Beatport is already on the backlog.'),
        ),
        migrations.AddConstraint(
            model_name='genrebacklog',
            constraint=models.UniqueConstraint(fields=('beatport_genre_id',), name='beatport_genre_id_unique_backlog', violation_error_message='This genre ID from Beatport is already on the backlog.'),
        ),
        migrations.AddConstraint(
            model_name='labelbacklog',
            constraint=models.UniqueConstraint(fields=('beatport_label_id',), name='beatport_label_id_unique_backlog', violation_error_message='This label ID from Beatport is already on the backlog.'),
        ),
        migrations.AddConstraint(
            model_name='trackbacklog',
            constraint=models.UniqueConstraint(fields=('beatport_track_id',), name='beatport_track_id_unique_backlog', violation_error_message='This track ID from Beatport is already on the backlog.'),
        ),
    ]
