# Generated by Django 5.2 on 2025-05-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_trackbacklog_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist404',
            options={'ordering': ['datetime_discovered', 'beatport_artist_id']},
        ),
        migrations.AlterModelOptions(
            name='artistbacklog',
            options={'ordering': ['datetime_discovered', 'beatport_artist_id']},
        ),
        migrations.AlterModelOptions(
            name='genre404',
            options={'ordering': ['datetime_discovered', 'beatport_genre_id']},
        ),
        migrations.AlterModelOptions(
            name='genrebacklog',
            options={'ordering': ['datetime_discovered', 'beatport_genre_id']},
        ),
        migrations.AlterModelOptions(
            name='label404',
            options={'ordering': ['datetime_discovered', 'beatport_label_id']},
        ),
        migrations.AlterModelOptions(
            name='labelbacklog',
            options={'ordering': ['datetime_discovered', 'beatport_label_id']},
        ),
        migrations.AlterModelOptions(
            name='track404',
            options={'ordering': ['datetime_discovered', 'beatport_track_id']},
        ),
        migrations.AlterModelOptions(
            name='trackbacklog',
            options={'ordering': ['datetime_discovered', 'beatport_track_id']},
        ),
    ]
