# Generated by Django 5.2 on 2025-05-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_alter_artist404_options_alter_artistbacklog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genrerequest',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genrerequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='label',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='remix_artist',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='track',
        ),
        migrations.RemoveField(
            model_name='trackrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArtistRequest',
        ),
        migrations.DeleteModel(
            name='GenreRequest',
        ),
        migrations.DeleteModel(
            name='TrackRequest',
        ),
    ]
